In [1]:
import numpy as np
from sklearn import preprocessing

In [2]:
x=np.array([[1.,-1.,2.],
            [2.,0.,0.],
            [0.,1.,-1.]])

In [9]:
x_scaled=preprocessing.scale(x)
x_scaled

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [6]:
x_scaled.mean(axis=0)

array([0., 0., 0.])

In [8]:
x_scaled.std(axis=0)

array([1., 1., 1.])

In [14]:
scaler=preprocessing.StandardScaler()
scaler.fit(x)

scaler.transform(x)

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [15]:
x_test=[[1,1,0]]
scaler.transform(x_test)

array([[ 0.        ,  1.22474487, -0.26726124]])